version: '3.7'

services:
  service1:
    image: thaiphuc2203/swarm:dotnet
    ports:
      - 8085:8085
    
    deploy:
      replicas: 5 # số tác vụ( container) được tạo ra trên 3 node
      resources:
        limits:
          cpus: '0.5' # tối đa 50% của 1 core
          memory: 100MB
        reservations:
          cpus: '0.25'
          memory: 40MB
      restart_policy: #  khởi động lại container
        condition: on-failure
  service2:
    image: thaiphuc2203/swarm:php
    ports:
      - 8086:8085
    
    deploy:
      replicas: 9
      resources:
        limits:
          cpus: '0.5' # tối đa 50% của 1 core
          memory: 100MB
        reservations:
          cpus: '0.25'
          memory: 40MB
      restart_policy: #  khởi động lại container
        condition: on-failure